server:
  port: 6878
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      security:
        user: admin
        pass: admin
  instance:
    hostname: eureka001
